// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKgNlkvZST5e0e-rfwhVyRObsXC_IGRO0',
    appId: '1:149853387039:web:2979a602ab7d77dd67982a',
    messagingSenderId: '149853387039',
    projectId: 'first-flutter-project-byciro',
    authDomain: 'first-flutter-project-byciro.firebaseapp.com',
    storageBucket: 'first-flutter-project-byciro.appspot.com',
    measurementId: 'G-ZTD449L5CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgyuz1O5BOzkXeegaGrBI1-NVHBGXy9QI',
    appId: '1:149853387039:android:5e47f0b5e50a577567982a',
    messagingSenderId: '149853387039',
    projectId: 'first-flutter-project-byciro',
    storageBucket: 'first-flutter-project-byciro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1M-4vZIJhkCiuORCy2IYHFAFFuftftDg',
    appId: '1:149853387039:ios:dff5d59f78a5c95567982a',
    messagingSenderId: '149853387039',
    projectId: 'first-flutter-project-byciro',
    storageBucket: 'first-flutter-project-byciro.appspot.com',
    iosClientId: '149853387039-jvmpn3uhdkbqn9etka5qvursk3olm9ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1M-4vZIJhkCiuORCy2IYHFAFFuftftDg',
    appId: '1:149853387039:ios:dff5d59f78a5c95567982a',
    messagingSenderId: '149853387039',
    projectId: 'first-flutter-project-byciro',
    storageBucket: 'first-flutter-project-byciro.appspot.com',
    iosClientId: '149853387039-jvmpn3uhdkbqn9etka5qvursk3olm9ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningDart',
  );
}
